# Generated by Django 6.0.2 on 2026-05-10 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_coursereview_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='review_type',
            field=models.CharField(choices=[('course', 'Відгук на курс'), ('school', 'Відгук про школу')], default='course', max_length=10, verbose_name='Тип відгуку'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(condition=models.Q(('review_type', 'course')), fields=('course', 'user'), name='unique_course_review_per_user'),
        ),
    ]
