# Generated by Django 6.0.2 on 2026-03-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='tblCategories',
        ),
        migrations.AlterModelTable(
            name='course',
            table='tblCourses',
        ),
        migrations.AlterModelTable(
            name='student',
            table='tblStudents',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='tblTeachers',
        ),
    ]
