# Generated by Django 6.0.2 on 2026-08-07 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_coursereview_review_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(condition=models.Q(('review_type', 'school')), fields=('user',), name='unique_school_review_per_user'),
        ),
    ]
