# Generated by Django 6.0.2 on 2026-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_course_teacher_course_teachers_coursegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='groups', to='myapp.teacher'),
        ),
    ]
