# Generated by Django 6.0.2 on 2026-03-31 19:43

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_coursegroup_teacher_coursegroup_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1200, 800], upload_to='courses_images/'),
        ),
    ]
