# Generated by Django 6.0.2 on 2026-04-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_newslettersubscriber_triallessonrequest_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='triallessonrequest',
            name='child_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вік дитини'),
        ),
        migrations.AddField(
            model_name='triallessonrequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course', verbose_name='Курс'),
        ),
    ]
